# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CodogenyDN
email: mathemaphysics@gmail.com
name: "CodogenyDN: Field Notes"
description: >- # this means to ignore newlines until "baseurl:"
        Trying to make better simulations
baseurl: 
url: http://mathemaphysics.github.io # the base hostname & protocol for your site, e.g. http://example.com
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
twitter_username: NuckChorris16
github_username:  mathemaphysics

#cover: "/test/fig001-delta-002-1.png"

# Build settings
markdown: kramdown
highlighter: pygments
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-coffeescript

feed:
  path: feed.xml

# Disqus Comments
# Leave shortname blank to disable comments site-wide.
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
disqus:
  shortname: codogenydn

scholar:
  style: american-institute-of-physics

github: [metadata]

show_downloads: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
