#!/bin/bash

git checkout source
git branch -D master
git checkout -b master
git filter-branch --subdirectory-filter _site/ -f
git checkout source
git push --all origin

# vim: tw=65:ts=4:sts=4:sw=4:et:sta
